name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: docker/build-push-action@v4
      with:
        file: ./sampleapp/Dockerfile
        push: false
        context: .
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myimg:v1
