name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        file: ./sampleapp/Dockerfile
    - name: Build the Docker image
      run: docker build -t myimg:v1 .
    - name: Run the container
      run: docker run -d --name myapp -p 8081:80 myimg:v1
    - run: sleep 10  
    - name: Test with curl
      run: curl -l localhost:8081
